### ISSUE TITLE
Separate healthcheck plugin

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/coredns#19]
We should create separate `neofs-health` plugin (that uses healht logic from `geodns` plugin).

**Comment by alexvanin** [comment]
More like `nns-health`. There is nothing about `neofs`, if I understand correctly.

**Comment by KirillovDenis** [comment]
By `neofs-nealth` I mean it belongs to `nspcc`. This plugin will be general so maybe it can be called `healthchecker` (just `health` is already taken)
