### ISSUE TITLE
Consider two NNS contracts in zone

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/coredns#32]
One NNS in mainnet (higher priority) and one in sidechain. Merge result.

**Comment by KirillovDenis** [comment]
Currently, we support zone transfer requests 
https://github.com/nspcc-dev/coredns/blob/e2e4fd5b102a68a4d1052397bbade9f79e7bfec3/plugin/nns/nns.go#L52

If we provide two contracts in `Corefile`:
```corefile
.:53 {
    nns http://morph-chain.neofs.devenv:30333 - .container
    nns http://main-chain.neofs.devenv:30333 08ad3db9b6d3e3016a48c64d12400823ef424f21 .container
}
```
how we should handle zone transfer requests (`AFXE`, `IFXR`)?

**Comment by alexvanin** [comment]
@realloc @anatoly-bogatyrev Any ideas?

**Comment by realloc** [comment]
I suggest constructing the resulting record set by taking the content from each contract and overriding in the order of appearance in config file. For an example config above, we take records from sidechain and override conflicting records with what was taken from mainnet.
  
 For production config I suggest using mainnet first and then override/extend it with sidechain records.

**Comment by KirillovDenis** [comment]
What should we do with SOA record (that must be the first and the last record in the response). This record also should be overridden by the last NNS contract from config?

**Comment by realloc** [comment]
I suggest taking SOA from the original (first in the order of appearance) zone.
